chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami/
  - gdscan=https://gdatasoftwareag.github.io/gdscan/
  - oci-registry=oci://ghcr.io/gdatasoftwareag/
helm-repo-extra-args:
  - oci-registry=--username=GdataGithubBot