{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "gdscan.fullname" . }}
  labels:
    {{- include "gdscan.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "gdscan.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
    - from:
      ports:
        - port: 8080 # Http
{{- end }}