{{- if .Values.imagePullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: gdscanregistry
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ required "You need to set the dockerconfigjson for the private registry" .Values.secret.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
{{- end -}}