apiVersion: v1
kind: Service
metadata:
  name: {{ include "gdscan.fullname" . }}
  labels:
    {{- include "gdscan.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: http
  selector:
    {{- include "gdscan.selectorLabels" . | nindent 4 }}
