gateway:
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: gateway.local
        paths:
          - path: /
            pathType: ImplementationSpecific
        service:
          name: ""
          port: 9090
      - host: upload.local
        paths:
          - path: /
            pathType: ImplementationSpecific
        service:
          name: ""
          port: 8080              
    tls: []

  secret:
    dockerconfigjson: ""

  nameOverride: ""
  fullnameOverride: ""
    
  networkPolicy:
    enabled: false
    ingress: []
    egress: []

  service:
    type: ""
    http:
      port: 8080
    ws:
      port: 9090
  
  metrics:
    enabled: false
    port: 8080
    path: /metrics

  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 20
    targetCPU: 75
    metrics:

  podDisruptionBudget:
    minAvailable: 1    
  
  replicaCount: 1
  revisionHistoryLimit: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 0.5
      memory: 256Mi  

  containerSecurityContext:
    enabled: false

  image:
    repository: ghcr.io/gdatasoftwareag/vaas/gateway
    pullPolicy: Always
    tag: latest

  env:

  imagePullSecrets: {}
  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  

scanner:
  replicaCount: 1
  deploymentStrategy: "Recreate"
  server:
    name: server
    image:
      repository: ghcr.io/gdatasoftwareag/scanserver
      pullPolicy: Always
      tag: 1.8.0
    containerSecurityContext:
      enabled: false
  client:
    name: client
    image:
      repository: ghcr.io/gdatasoftwareag/scanclient
      pullPolicy: Always
      tag: 1.8.0
    containerSecurityContext:
      enabled: false
  terminationGracePeriodSeconds: 30

  imagePullSecrets:
    - name: scannerregistry

  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  secret:
    dockerconfigjson: ""

  service:
    type: ""
    port: 8080

  metrics:
    servicemonitor:
      enabled: false
      port: 8080
      path: /metrics

  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: scanner.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

  resources:
    server:
      limits:
        memory: 2Gi
      requests:
        cpu: 2
        memory: 2Gi
    client:
      limits:
        memory: 128Mi
      requests:
        cpu: 1
        memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 20
    targetCPU: 75
    metrics:

  nodeSelector: {}

  tolerations: []

  affinity: {}

  persistence:
    enabled: false
    accessMode: ReadWriteOnce
    memory: false
    size: 5Gi
    storageClass: ""

  autoUpdate:
    image:
      registry: docker.io
      repository: bitnami/kubectl
      tag: latest
    containerSecurityContext:
      enabled: false
    enabled: true
    # every hour
    schedule: "0 * * * *"
    networkPolicy:
      enabled: true
      k8sApiPort: 6443
