#TODO: Check if Values in range are correct
{{- if .Values.gateway.ingress.enabled -}}
{{- $fullName := include "gateway.fullname" . -}}
{{- if and .Values.gateway.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.gateway.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.gateway.ingress.annotations "kubernetes.io/ingress.class" .Values.gateway.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  {{- with .Values.gateway.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.gateway.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.gateway.ingress.className }}
  {{- end }}
  {{- if .Values.gateway.ingress.tls }}
  tls:
    {{- range .Values.gateway.ingress.tls }}
    - hosts:
        {{- range .Values.gateway.ingress.hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .Values.gateway.ingress.secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.gateway.ingress.hosts }}
    - host: {{ .Values.gateway.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.gateway.ingress.hosts.path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .Values.gateway.ingress.hosts.pathtype }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ .Values.gateway.ingress.hosts.service.name }}
                port:
                  number: {{ .Values.gateway.ingress.hosts.service.port }}
              {{- else }}
              serviceName: {{ .Values.gateway.ingress.hosts.service.name }}
              servicePort: {{ .Values.gateway.ingress.hosts.service.port }}
              {{- end }}                  
    {{- end }}    
{{- end }}
