x-healthcheck-web: &healthcheck-web
  # Simpler port check
  # test: ["CMD", "/bin/sh", "-c", "nc -z localhost 8080 || exit 1"]
  test: [ "CMD", "/bin/sh", "-c", "exec 3<>/dev/tcp/localhost/8080; echo -e \"GET /health HTTP/1.1\\r\\nHost: localhost\\r\\n\\r\\n\" >&3; grep \"200 OK\" <&3" ]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 20s
  
services:
    gdscan:
    image: ghcr.io/gdatasoftwareag/vaas/scanner:1.13.1
    deploy: 
      resources:
        limits:
          cpus: '2'
          memory: 4G
    healthcheck:
      <<: *healthcheck-web
    ports:
      - "8080:8080"
    networks:
      - vaas
  
networks:
  vaas:
    driver: bridge