{{- if and .Values.scanner.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "scanner.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "scanner.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    {{- if and (.Values.scanner.persistence.enabled) (eq .Values.scanner.persistence.accessMode "ReadWriteOnce" ) }}
    kind: StatefulSet
    {{- else }}
    kind: Deployment
    {{- end }}
    name: {{ include "scanner.fullname" . }}
  minReplicas: {{ .Values.scanner.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.scanner.autoscaling.maxReplicas }}
  {{- if .Values.scanner.autoscaling.metrics }}
  metrics: {{- toYaml .Values.scanner.autoscaling.metrics | nindent 4 }}
  {{- else }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.scanner.autoscaling.targetCPU }}
  {{- end }}
{{- end }}