apiVersion: v1
kind: Service
metadata:
  name: {{ include "scanner.fullname" . }}
  labels:
    {{- include "scanner.labels" . | nindent 4 }}
spec:
  type: {{ .Values.scanner.service.type }}
  ports:
    - port: {{ .Values.scanner.service.port }}
      targetPort: api
      protocol: TCP
      name: http
  selector:
    {{- include "scanner.selectorLabels" . | nindent 4 }}
