{{- if and (.Values.scanner.persistence.enabled) (eq .Values.scanner.persistence.accessMode "ReadWriteOnce" ) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "scanner.fullname" . }}
  labels:
    {{- include "scanner.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "scanner.fullname" . }}
  {{- if not .Values.scanner.autoscaling.enabled }}
  replicas: {{ .Values.scanner.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "scanner.selectorLabels" . | nindent 6 }}
  volumeClaimTemplates:
    - metadata:
        name: samples
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- include "common.storage.class" (dict "persistence" .Values.scanner.persistence "global" .Values.scanner.global) | nindent 8 }}
        resources:
          requests:
            storage: {{ .Values.scanner.persistence.size | quote }}
  template:
    metadata:
      {{- with .Values.scanner.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "scanner.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.scanner.imagePullSecrets }}
      imagePullSecrets: 
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: server-tmp
          emptyDir: {}
        - name: scan-socket
          emptyDir: {}
          {{- if .Values.scanner.client.containerSecurityContext.enabled }}
        - name: client-tmp
          emptyDir: {}
          {{- end }}
          {{- if .Values.scanner.server.containerSecurityContext.enabled }}
        - name: server-var-log
          emptyDir: {}
          {{- end }}
      containers:
        - name: {{ .Values.scanner.server.name }}
          env:
            - name: date
              value: "{{ now | unixEpoch }}"
          image: "{{ .Values.scanner.server.image.repository }}:{{ .Values.scanner.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.scanner.server.image.pullPolicy }}
          {{- if .Values.scanner.server.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.scanner.server.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: server-tmp
              mountPath: /tmp
            - name: samples
              mountPath: /tmp/scan
            - name: scan-socket
              mountPath: /var/share/run
              {{- if .Values.scanner.server.containerSecurityContext.enabled }}
            - name: server-var-log
              mountPath: /var/log
              {{- end }}
          resources:
            {{- toYaml .Values.scanner.resources.server | nindent 12 }}
        - name: {{ .Values.scanner.client.name }}
          image: "{{ .Values.scanner.client.image.repository }}:{{ .Values.scanner.client.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.scanner.client.image.pullPolicy }}
          {{- if .Values.scanner.client.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.scanner.client.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: samples
              mountPath: /tmp/scan
            - name: scan-socket
              mountPath: /var/share/run
              {{- if .Values.scanner.client.containerSecurityContext.enabled }}
            - name: client-tmp
              mountPath: /tmp
              {{- end }}
          resources:
            {{- toYaml .Values.scanner.resources.client | nindent 12 }}
          ports:
            - name: api
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: api
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: api
            initialDelaySeconds: 5
            periodSeconds: 5
      terminationGracePeriodSeconds: {{ .Values.scanner.terminationGracePeriodSeconds }}       
      {{- with .Values.scanner.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scanner.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scanner.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}