{{- if .Values.gateway.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "gateway.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
    - from:
      ports:
        - port: 8080 # Upload
        - port: 9090 # Websocket
  egress:
    - to:
      ports:
        - port: 443 # VerdictRequestForUrl
        - port: 80  # VerdictRequestForUrl
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redis
      ports:
        - port: 6379
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: gdscan
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: mini-identity-provider
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: gateway              
      ports:
        - port: 8080
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP     
    {{- if or .Values.gateway.networkPolicy.ingressNSMatchLabels .Values.gateway.networkPolicy.ingressNSPodMatchLabels }}
    - from:
        - namespaceSelector:
            matchLabels:
              {{- if .Values.gateway.networkPolicy.ingressNSMatchLabels }}
                {{- range $key, $value := .Values.gateway.networkPolicy.ingressNSMatchLabels }}
                {{ $key | quote }}: {{ $value | quote }}
                {{- end }}
              {{ else }}
                {}
              {{- end }}
          {{- if .Values.gateway.networkPolicy.ingressNSPodMatchLabels }}
          podSelector:
            matchLabels:
              {{- range $key, $value := .Values.gateway.networkPolicy.ingressNSPodMatchLabels }}
              {{ $key | quote }}: {{ $value | quote }}
              {{- end }}
          {{- end }}
      ports:
        - port: 8080 # Upload
    {{- end }}
{{- end }}