{{- if .Values.gateway.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "gateway.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
    - from:
      ports:
        - port: 8080 # Http
        - port: 9090 # Websocket
  egress:
    - to:
      ports:
        - port: 443 # VerdictRequestForUrl
        - port: 80  # VerdictRequestForUrl
        - port: 6379 # Redis
        - port: 8080 # GdScan
        - port: 9090 # Cloud Gateway
{{- end }}