{{- if gt .Values.gateway.replicaCount 1.0  }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gateway.selectorLabels" . | nindent 6 }}
  minAvailable: {{ .Values.gateway.podDisruptionBudget.minAvailable }}
{{- end }}