{{- if .Values.imagePullSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.fullname" . }}-image-pull-secret
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ .Values.imagePullSecret }}
type: kubernetes.io/dockerconfigjson
{{- end }}
{{- if ((.Values.global).secret).imagePullSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.fullname" . }}-global-image-pull-secret
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ .Values.global.secret.imagePullSecret }}
type: kubernetes.io/dockerconfigjson
{{- end }}
{{- if ((.Values.global).secret).dockerconfigjson }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.fullname" . }}-global-dockerconfigjson
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ .Values.global.secret.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
{{- end }}