{{- if .Values.global.imagePullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: registry
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ required "You need to set the dockerconfigjson for the private registry" .Values.global.secret.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
{{- end -}}