apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.gateway.service.ws.port }}
      targetPort: ws
      protocol: TCP
      name: ws
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
